codecov:
  bot: this-is-codecov-bot
comment:
  layout: "diff"
  behavior: default
  require_changes: true  # if true: only post the comment if coverage changes
  branches:               # branch names that can post comment
    - "master"
coverage:	
  status:
      project:
        default:
          target: 50%
          threshold: 25%
          base: auto
          flags: 
            - frontend
  range: "40..100"
  round: up
  precision: 2
  parsers:	
    javascript:	
      enable_partials: no 
  paths: "./coverage/clover.xml"