codecov:
  bot: this-is-codecov-bot
coverage:	
  status:
      project:
        default:
          target: 50
          threshold: 25%
          base: auto
          flags: 
            - frontend
  range: 40..100
  round: up
  precision: 2
  parsers:	
    javascript:	
      enable_partials: no 
  paths: "./coverage/clover.xml"