codecov:
  bot: this-is-codecov-bot
comment:
  require_changes: true
coverage:
  status:
    project:
      default:
        threshold: 40%
        base: auto
        flags:
          - frontend
  range: 40..100
  round: down
  precision: 2
  parsers:
    javascript:
      enable_partials: no